specs
data

	^ {
		{'Create morph'. '[Morph new]'}.
		{'Create iconic button'. '[IconicButton new]'}.
		{'Create <b>ui</b> push button'. '[UiPushButton new icon: UiSilkIcons diskIcon]'}.
		{'Create scroll bar'. '[ScrollBar new]'}.
		{'Create <b>ui</b> scroll bar'. '[UiScrollBar new]'}.
		{'Create scroll pane'. '[ScrollPane new]'}.
		{'Create <b>ui</b> scroll area'. '[UiScrollArea new]'}.
		{'Create pluggable text morph'. '[PluggableTextMorph new]'}.
		{'Create <b>ui</b> text edit'. '[UiTextEdit new]'}.
		{'Create pluggable list'. '[PluggableListMorph new]'}.
		{'Create <b>ui</b> list view'. '[UiListView new]'}.
		{'Create book morph.'. '[BookMorph new insertPage]'}.
		{'Create <b>ui</b> stacked widget.'. '[UiStackedWidget new addPage]'}
	}